"""alterando data para date

Revision ID: b0e970e4ce6d
Revises: 0a22b46c03a0
Create Date: 2024-01-29 12:49:24.082815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0e970e4ce6d'
down_revision: Union[str, None] = '0a22b46c03a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
